foreground              #f1dfdc
background              #1a1110
cursor                  #ffb4a8

active_tab_foreground   #1a1110
active_tab_background   #f1dfdc
inactive_tab_foreground #f1dfdc
inactive_tab_background #1a1110

active_border_color     #ffb4a8
inactive_border_color   #1a1110
bell_border_color       #dec48c

color0                  #1a1110
color1                  #ffb4ab
color2                  #e7bdb6
color3                  #dec48c
color4                  #ffb4a8
color5                  #dec48c
color6                  #e7bdb6
color7                  #f1dfdc
color8                  #a08c89
color9                  #ffb4ab
color10                 #e7bdb6
color11                 #dec48c
color12                 #ffb4a8
color13                 #dec48c
color14                 #e7bdb6
color15                 #f1dfdc
