bind = SUPER, W, exec, ~/.config/hypr/scripts/wallpaper-picker.sh
bind = SUPER SHIFT, W, exec, ~/.config/hypr/scripts/wallpaper-picker.sh
bind = SUPER, P, exec, /home/sairaj/.config/hypr/scripts/wallpaper-picker.sh
