exec-once = swaync
exec-once = swww-daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = /home/sairaj/.config/hypr/scripts/launch-waybar.sh
exec-once = swww img /home/sairaj/Wallpapers/aesthetic_deer.png
