exec-once = swaync
exec-once = swww-daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = sleep 2 && waybar -c "/home/sairaj/.config/waybar/configs/[TOP] Matugen" -s "/home/sairaj/.config/waybar/style/[Matugen] Minimal.css"
exec-once = sleep 1 && ~/.config/hypr/scripts/wallpaper.sh /home/sairaj/Wallpapers/Red_samurai.png
exec-once = hypridle
