background {
    monitor =
    path = /home/sairaj/Wallpapers/Red_samurai.png
    blur_passes = 4
    contrast = 0.9
    brightness = 0.6
    vibrancy = 0.3
    vibrancy_darkness = 0.1
}

label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/marathi-time.sh)"
    color = rgba(255, 255, 255, 0.95)
    font_size = 140
    font_family = Noto Sans Devanagari
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/marathi-date.sh)"
    color = rgba(255, 255, 255, 0.65)
    font_size = 22
    font_family = Noto Sans Devanagari
    position = 0, 20
    halign = center
    valign = center
}

label {
    monitor =
    text = सुस्वागतम्, $USER
    color = rgba(255, 255, 255, 0.30)
    font_size = 15
    font_family = Noto Sans Devanagari
    position = 0, -50
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgba(255, 255, 255, 0.9)
    fade_on_empty = true
    font_family = Noto Sans Devanagari
    placeholder_text =
    hide_input = false
    rounding = 15
    position = 0, -120
    halign = center
    valign = center
}
